### ISSUE TITLE
Feature: User can view their favorite skins.

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorite skins.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a favorites functionality that allows the user to easily favorite skins, delete skins, and view skins.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/ajax-project/assets/66459527/c5ba335b-dae1-4658-9de0-8e09334d0153)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/e154ea8a-966f-4312-b3c0-aec3cbc7caed)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a favorites page and add on the view "favorites-page" to the viewSwap function. 
- [ ] Create title and subtitle for favorites.
- [ ] Create favorites toggler (open and solid) inside the skin container.
- [ ] Create a function that will take the closest skin-container and save it into local storage.
- [ ] Create a function that will take the favorites from the local storage to render and append the favorites inside the favorites page.
- [ ] Create a function that will delete favorite skins from the favorites page.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
